### ISSUE TITLE
It works like a redirect rather than mirror?

### ISSUE THREAD

**Issue by hyp530** [robertdebock/mirror#5]
I tried `docker run -p 443:443 -e "URL=https://google.com" robertdebock/mirror`

The browser will be redirected to Google.com. It's not a mirror. Any solution?

Thank you very much.

**Comment by robertdebock** [comment]
Thanks for your issue, only seeing it now. I'll try and see if the image needs a change.

**Comment by robertdebock** [comment]
It tools like the `URL` needs to be exactly what you're ending up on.

The container uses Apache using [ProxyPassReverse](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost). This requires the `URL` parameter to be exact. In your example that would mean:

```
docker run -p 443:443 -e "URL=https://www.google.com/" robertdebock/mirror
```

(I added `www` and a trailing `/`.)

Google shows a blank page for me, but mirroring my personal website works using:

```
docker run -p 8443:443 -e "URL=https://robertdebock.nl/" robertdebock/mirror
```

The README.md currently describes:

```
- `-e "URL=https://www.flickr.com/photos/robertdebock"` - Setup the (Apache) proxy to map a custom URL to https://www.flickr.com/photos/robertdebock. It's best to (try to) open the website in a browser, let all redirects take place and use the final URL. In case you'd like to mirror the homepage, ensure you end the URL with a / . Like so https://bla.com/
```

If you know a better way to describe it, please tell me or make a pull-request.

Thanks for your input, hope you're able to continue.
